"""add service table

Revision ID: 4d3b04c245f5
Revises: 4d07b270c593
Create Date: 2026-04-19 12:37:37.473764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3b04c245f5'
down_revision: Union[str, Sequence[str], None] = '4d07b270c593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.drop_table('check_in_sub')
    op.drop_table('customer_tools')
    op.drop_table('customer_communication_log')
    op.drop_table('customer_contact')
    op.drop_table('unit')
    op.drop_table('customer_address')
    op.drop_table('market')
    op.drop_table('customer_application')
    op.drop_table('customer_tools_sub')
    op.drop_table('classification')
    op.drop_table('customer_market')
    op.drop_table('customer_application_specs')
    op.drop_table('check_in')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_in',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('received_at', sa.DATETIME(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_application_specs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('application_id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['customer_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_market',
    sa.Column('customer_market_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('market_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['market.market_id'], ),
    sa.PrimaryKeyConstraint('customer_market_id')
    )
    op.create_table('classification',
    sa.Column('classification_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('classification_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customer_tools_sub',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tool_id', sa.INTEGER(), nullable=False),
    sa.Column('sub_type', sa.VARCHAR(), nullable=True),
    sa.Column('value', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['customer_tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_application',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market',
    sa.Column('market_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('market_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customer_address',
    sa.Column('address_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('address_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('street', sa.VARCHAR(length=100), nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), nullable=False),
    sa.Column('state', sa.VARCHAR(length=50), nullable=False),
    sa.Column('zip_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('unit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_contact',
    sa.Column('contact_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('position', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('customer_communication_log',
    sa.Column('log_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('customer_tools',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('serial_number', sa.VARCHAR(), nullable=False),
    sa.Column('fab_number', sa.VARCHAR(), nullable=True),
    sa.Column('model_info', sa.VARCHAR(), nullable=True),
    sa.Column('unit_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_in_sub',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('check_in_id', sa.INTEGER(), nullable=False),
    sa.Column('tool_id', sa.INTEGER(), nullable=False),
    sa.Column('inspected', sa.BOOLEAN(), nullable=False),
    sa.Column('quoted', sa.BOOLEAN(), nullable=False),
    sa.Column('approved', sa.BOOLEAN(), nullable=False),
    sa.Column('closed', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['check_in_id'], ['check_in.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('customer', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cardcode', sa.VARCHAR(length=75), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('website', sa.VARCHAR(length=50), nullable=True),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.Column('repair instructions', sa.TEXT(), nullable=True),
    sa.Column('multiplier', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('lead id', sa.INTEGER(), nullable=True),
    sa.Column('responsibility id', sa.INTEGER(), nullable=True),
    sa.Column('calibration interval', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    # ### end Alembic commands ###
