"""add customer_contact table

Revision ID: 5efc52427fa4
Revises: 495af0c84c13
Create Date: 2026-04-19 11:52:05.224611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efc52427fa4'
down_revision: Union[str, Sequence[str], None] = '495af0c84c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.drop_table('customer_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_address',
    sa.Column('address_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('address_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('street', sa.VARCHAR(length=100), nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), nullable=False),
    sa.Column('state', sa.VARCHAR(length=50), nullable=False),
    sa.Column('zip_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('customer',
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('customer', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cardcode', sa.VARCHAR(length=75), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('website', sa.VARCHAR(length=50), nullable=True),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.Column('repair instructions', sa.TEXT(), nullable=True),
    sa.Column('multiplier', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('lead id', sa.INTEGER(), nullable=True),
    sa.Column('responsibility id', sa.INTEGER(), nullable=True),
    sa.Column('calibration interval', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    # ### end Alembic commands ###
