"""add customer_tools and customer_tools_sub tables

Revision ID: 92806fd80e9a
Revises: 1a02b6d51437
Create Date: 2026-04-19 12:05:16.402795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92806fd80e9a'
down_revision: Union[str, Sequence[str], None] = '1a02b6d51437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market')
    op.drop_table('customer_contact')
    op.drop_table('customer_address')
    op.drop_table('customer_communication_log')
    op.drop_table('customer_market')
    op.drop_table('customer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('customer', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cardcode', sa.VARCHAR(length=75), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('website', sa.VARCHAR(length=50), nullable=True),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.Column('repair instructions', sa.TEXT(), nullable=True),
    sa.Column('multiplier', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('lead id', sa.INTEGER(), nullable=True),
    sa.Column('responsibility id', sa.INTEGER(), nullable=True),
    sa.Column('calibration interval', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('customer_market',
    sa.Column('customer_market_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('market_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['market.market_id'], ),
    sa.PrimaryKeyConstraint('customer_market_id')
    )
    op.create_table('customer_communication_log',
    sa.Column('log_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('customer_address',
    sa.Column('address_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('address_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('street', sa.VARCHAR(length=100), nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), nullable=False),
    sa.Column('state', sa.VARCHAR(length=50), nullable=False),
    sa.Column('zip_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('customer_contact',
    sa.Column('contact_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('position', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('market',
    sa.Column('market_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('market_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
